@echo off
setlocal EnableDelayedExpansion

::: Third Space Vest - Python Setup Check
::: Checks Python installation and helps configure .env.bat
:::
::: Usage: call setup\check-python.bat
:::
::: Sets TSV_PYTHON on success (exported to caller)
::: Exits with error code 1 on failure

echo [CHECK] Checking Python installation...

:: Load existing .env.bat if present
if exist "%~dp0..\.env.bat" call "%~dp0..\.env.bat"

:: Detect Python using unified logic: TSV_PYTHON -> py -3.14 -> python/python3
set "DETECTED_PYTHON="
set "DETECTED_VERSION="
set "DETECTION_METHOD="

:: 1. Check if TSV_PYTHON is already set (from .env.bat)
if defined TSV_PYTHON (
    set "DETECTED_PYTHON=%TSV_PYTHON%"
    set "DETECTION_METHOD=TSV_PYTHON environment variable"
    goto :verify_python
)

:: 2. Try py launcher with Python 3.14 (preferred)
where py >nul 2>&1
if !ERRORLEVEL! equ 0 (
    py -3.14 -c "import sys" >nul 2>&1
    if !ERRORLEVEL! equ 0 (
        set "DETECTED_PYTHON=py -3.14"
        set "DETECTION_METHOD=py launcher (Python 3.14)"
        goto :verify_python
    )

)


:: No Python found
echo   [FAIL] Python is not installed!
echo.
echo   Please install Python 3.14+:
echo     1. Go to https://www.python.org/downloads/
echo     2. Download Python 3.14 or newer
echo     3. Run installer, CHECK "Add to PATH"
echo     4. Restart your terminal
echo.
exit /b 1

:verify_python
:: Get Python version
for /f "tokens=*" %%i in ('%DETECTED_PYTHON% --version 2^>^&1') do set "DETECTED_VERSION=%%i"

:: Verify it actually works
%DETECTED_PYTHON% -c "import sys; exit(0 if sys.version_info >= (3, 9) else 1)" >nul 2>&1
if !ERRORLEVEL! neq 0 (
    echo   [FAIL] %DETECTED_VERSION% is too old or not working
    echo   Please install Python 3.14+ from https://www.python.org/downloads/
    exit /b 1
)

:: Get major.minor version
for /f "tokens=*" %%i in ('%DETECTED_PYTHON% -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"') do set "PY_VERSION=%%i"

echo   [OK] %DETECTED_VERSION%
echo        Detected via: %DETECTION_METHOD%
echo        Command: %DETECTED_PYTHON%

:: Check if we should offer to save to .env.bat
if not exist "%~dp0..\.env.bat" (
    echo.
    echo   Would you like to save this Python as your preferred version?
    echo   This creates windows\.env.bat so all scripts use the same Python.
    echo.
    set /p "SAVE_ENV=  Save to .env.bat? [Y/n]: "
    if /i "!SAVE_ENV!"=="" set "SAVE_ENV=Y"
    if /i "!SAVE_ENV!"=="Y" (
        echo @echo off> "%~dp0..\.env.bat"
        echo REM Third Space Vest - Python configuration>> "%~dp0..\.env.bat"
        echo REM Auto-generated by check-setup.bat>> "%~dp0..\.env.bat"
        echo REM Edit this file to change Python version>> "%~dp0..\.env.bat"
        echo.>> "%~dp0..\.env.bat"
        echo set "TSV_PYTHON=%DETECTED_PYTHON%">> "%~dp0..\.env.bat"
        echo.
        echo   [OK] Created windows\.env.bat with TSV_PYTHON=%DETECTED_PYTHON%
    )
) else (
    if not defined TSV_PYTHON (
        echo.
        echo   [INFO] windows\.env.bat exists but TSV_PYTHON is not set.
        echo          Consider adding: set "TSV_PYTHON=%DETECTED_PYTHON%"
    )
)

:: Export TSV_PYTHON for caller
set "EXPORT_PYTHON=%DETECTED_PYTHON%"
endlocal & set "TSV_PYTHON=%EXPORT_PYTHON%"
exit /b 0
